# Generated by Django 3.0.1 on 2020-01-14 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 11, 10, 37, 364257, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
